In [74]:
import pandas as pd
import numpy as np

In [75]:
df = pd.read_excel('./Pre-Data/2024-2025.xlsx')

In [76]:
df = df.drop(index=[1,2,3,4,5])

In [77]:
df.columns = df.iloc[6]

df = df.iloc[7:].reset_index(drop=True)

df.columns.name = None

In [78]:
df.head()

,2,ANDAMAN AND NICOBAR ISLANDS,NICOBAR,NaN,0,2805.2,2805.2,2805.2,0,37247,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9911.13,313.56
0,3,ANDAMAN AND NICOBAR ISLANDS,SOUTH ANDAMAN,NaN,0,3015.7,0,3015.7,0,31524,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9717.96,0
1,4,ANDHRA PRADESH,Alluri Sitharama Raju,NaN,0,1257.832755,0,1257.832755,0,639234.675995,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50117.56,0
2,5,ANDHRA PRADESH,Anakapalli,NaN,1205.747378,1176.354436,0,1182.552833,73066,273414.65992,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1317238.51,0
3,6,ANDHRA PRADESH,Ananthapuramu,NaN,514.40619,515.242709,0,515.027156,243887,702592.33,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119813.93,0
4,7,ANDHRA PRADESH,Annamayya,NaN,731.50343,751.516317,0,748.14514,112199,553867,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84922.96,0

In [79]:
df.describe()

,2,ANDAMAN AND NICOBAR ISLANDS,NICOBAR,NaN,0,2805.2,2805.2,2805.2,0,37247,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9911.13,313.56
count,734,733,733,0,727,727,727,727,734,727,...,686,0,4,0,11,7,4,0,727,727
unique,734,37,731,0,439,518,79,681,476,549,...,44,0,1,0,1,1,1,0,710,84
top,3,UTTAR PRADESH,BALRAMPUR,NaN,0,0,0,0,0,0,...,0,NaN,0,NaN,0,0,0,NaN,0,0
freq,1,75,2,NaN,274,179,648,15,259,179,...,643,NaN,4,NaN,11,7,4,NaN,18,644

In [80]:
df2 = pd.read_csv('2024-2025.csv')

In [81]:
df2

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 143,Unnamed: 144,Unnamed: 145,Unnamed: 146,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152
0,"""Report"" for : ANDAMAN AND NICOBAR ISLANDS for...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Assessment Year,2024-2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Top View,DISTRICT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,View,admin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Computation Type,normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,732,WEST BENGAL,PURBA MEDINIPUR,NaN,0,1670,1670,1670,0,164955,...,278047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,402648,0
742,733,WEST BENGAL,PURULIYA,NaN,0,1363,0,1363,0,619313,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185917,0
743,734,WEST BENGAL,SOUTH 24 PARGANAS,NaN,0,0,1624,1624,0,0,...,428982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
744,735,WEST BENGAL,UTTAR DINAJPUR,NaN,1922,1922,0,1922,18645,300638,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2493443,0
745,Total,NaN,NaN,NaN,888,1189,540,1055,71897444,157402028,...,186862177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165598161,5202640

In [82]:
df2.drop(index=[0,1,2,3,4,5])

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 143,Unnamed: 144,Unnamed: 145,Unnamed: 146,Unnamed: 147,Unnamed: 148,Unnamed: 149,Unnamed: 150,Unnamed: 151,Unnamed: 152
6,S.No,STATE,DISTRICT,ASSESSMENT UNIT,Rainfall (mm),NaN,NaN,NaN,Total Geographical Area (ha),NaN,...,Total Confined Ground Water Resources (ham),NaN,Dynamic Semi Confined Ground Water Resources (...,NaN,In-Storage Semi Confined Ground Water Resource...,NaN,Total Semi-Confined Ground Water Resources (ham),NaN,Total Ground Water Availability in the area (ham),NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Recharge Worthy Area (ha),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,C,NC,PQ,Total,C,NC,...,Fresh,Saline,Fresh,Saline,Fresh,Saline,Fresh,Saline,Fresh,Saline
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1,ANDAMAN AND NICOBAR ISLANDS,N & M ANDAMAN,NaN,0,3016,0,3016,0,58040,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14875,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
741,732,WEST BENGAL,PURBA MEDINIPUR,NaN,0,1670,1670,1670,0,164955,...,278047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,402648,0
742,733,WEST BENGAL,PURULIYA,NaN,0,1363,0,1363,0,619313,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,185917,0
743,734,WEST BENGAL,SOUTH 24 PARGANAS,NaN,0,0,1624,1624,0,0,...,428982,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
744,735,WEST BENGAL,UTTAR DINAJPUR,NaN,1922,1922,0,1922,18645,300638,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2493443,0
745,Total,NaN,NaN,NaN,888,1189,540,1055,71897444,157402028,...,186862177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,165598161,5202640

In [83]:
df2.columns = df.iloc[1]

In [84]:
df3 = pd.read_csv("2024-2025.csv", skiprows=7) 

# CORRECTED LINE:
# 1. df.columns ki jagah 'df3.columns'
# 2. str(c) add kiya taaki numbers bhi string ban jayein
df3.columns = [str(c).replace('\n', ' ').strip() for c in df3.columns]

# Check karne ke liye print karein
print("Columns cleaned successfully!")
print(df3.columns)
print(df3.head())

Columns cleaned successfully!
Index(['S.No', 'STATE', 'DISTRICT', 'ASSESSMENT UNIT', 'Rainfall (mm)',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Total Geographical Area (ha)', 'Unnamed: 9',
       ...
       'Total Confined Ground Water Resources (ham)', 'Unnamed: 144',
       'Dynamic Semi Confined Ground Water Resources (ham)', 'Unnamed: 146',
       'In-Storage Semi Confined Ground Water Resources (ham)', 'Unnamed: 148',
       'Total Semi-Confined Ground Water Resources (ham)', 'Unnamed: 150',
       'Total Ground Water Availability in the area (ham)', 'Unnamed: 152'],
      dtype='object', length=153)
  S.No                        STATE       DISTRICT  ASSESSMENT UNIT  \
0  NaN                          NaN            NaN              NaN
1  NaN                          NaN            NaN              NaN
2  NaN                          NaN            NaN              NaN
3    1  ANDAMAN AND NICOBAR ISLANDS  N & M ANDAMAN              NaN
4    2  ANDAMAN AND NICOBAR ISLANDS        NICOBAR              NaN

  Rainfall (mm) Unnamed: 5 Unnamed: 6 Unnamed: 7 Total Geographical Area (ha)  \
0           NaN        NaN        NaN        NaN    Recharge Worthy Area (ha)
1             C         NC         PQ      Total                            C
2           NaN        NaN        NaN        NaN                          NaN
3             0       3016          0       3016                            0
4             0       2805       2805       2805                            0

  Unnamed: 9  ... Total Confined Ground Water Resources (ham) Unnamed: 144  \
0        NaN  ...                                         NaN          NaN
1         NC  ...                                       Fresh       Saline
2        NaN  ...                                         NaN          NaN
3      58040  ...                                           0          NaN
4      37247  ...                                           0          NaN

  Dynamic Semi Confined Ground Water Resources (ham) Unnamed: 146  \
0                                                NaN          NaN
1                                              Fresh       Saline
2                                                NaN          NaN
3                                                NaN          NaN
4                                                NaN          NaN

  In-Storage Semi Confined Ground Water Resources (ham) Unnamed: 148  \
0                                                NaN             NaN
1                                              Fresh          Saline
2                                                NaN             NaN
3                                                NaN             NaN
4                                                NaN             NaN

  Total Semi-Confined Ground Water Resources (ham) Unnamed: 150  \
0                                              NaN          NaN
1                                            Fresh       Saline
2                                              NaN          NaN
3                                              NaN          NaN
4                                              NaN          NaN

  Total Ground Water Availability in the area (ham) Unnamed: 152
0                                               NaN          NaN
1                                             Fresh       Saline
2                                               NaN          NaN
3                                             14875            0
4                                              9911          314

[5 rows x 153 columns]

In [85]:
df3.head()

,S.No,STATE,DISTRICT,ASSESSMENT UNIT,Rainfall (mm),Unnamed: 5,Unnamed: 6,Unnamed: 7,Total Geographical Area (ha),Unnamed: 9,...,Total Confined Ground Water Resources (ham),Unnamed: 144,Dynamic Semi Confined Ground Water Resources (ham),Unnamed: 146,In-Storage Semi Confined Ground Water Resources (ham),Unnamed: 148,Total Semi-Confined Ground Water Resources (ham),Unnamed: 150,Total Ground Water Availability in the area (ham),Unnamed: 152
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Recharge Worthy Area (ha),NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,C,NC,PQ,Total,C,NC,...,Fresh,Saline,Fresh,Saline,Fresh,Saline,Fresh,Saline,Fresh,Saline
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,ANDAMAN AND NICOBAR ISLANDS,N & M ANDAMAN,NaN,0,3016,0,3016,0,58040,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14875,0
4,2,ANDAMAN AND NICOBAR ISLANDS,NICOBAR,NaN,0,2805,2805,2805,0,37247,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9911,314

In [155]:
df_raw = pd.read_excel("./Pre-Data/2012-2013.xlsx", header=None)

In [156]:
header_rows = df_raw.iloc[7:10].copy()

In [157]:
header_rows[8]

7    Total Geographical Area (ha)
8       Recharge Worthy Area (ha)
9                               C
Name: 8, dtype: object

In [158]:
header_rows = header_rows.ffill(axis=1)
header_rows

,0,1,2,3,4,5,6,7,8,9,...,143,144,145,146,147,148,149,150,151,152
7,S.No,STATE,DISTRICT,ASSESSMENT UNIT,Rainfall (mm),Rainfall (mm),Rainfall (mm),Rainfall (mm),Total Geographical Area (ha),Total Geographical Area (ha),...,Total Confined Ground Water Resources (ham),Total Confined Ground Water Resources (ham),Dynamic Semi Confined Ground Water Resources (...,Dynamic Semi Confined Ground Water Resources (...,In-Storage Semi Confined Ground Water Resource...,In-Storage Semi Confined Ground Water Resource...,Total Semi-Confined Ground Water Resources (ham),Total Semi-Confined Ground Water Resources (ham),Total Ground Water Availability in the area (ham),Total Ground Water Availability in the area (ham)
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Recharge Worthy Area (ha),Recharge Worthy Area (ha),...,Other Parameters Present,Other Parameters Present,Other Parameters Present,Other Parameters Present,Other Parameters Present,Other Parameters Present,Other Parameters Present,Other Parameters Present,Other Parameters Present,Other Parameters Present
9,NaN,NaN,NaN,NaN,C,NC,PQ,Total,C,NC,...,Fresh,Saline,Fresh,Saline,Fresh,Saline,Fresh,Saline,Fresh,Saline

In [159]:
new_columns = []
for i in range(header_rows.shape[1]):
    # Har column ke liye charo rows ki values uthayein
    parts = header_rows.iloc[:, i].astype(str).tolist()
    
    # 'nan' aur extra spaces hatayein
    clean_parts = [p.strip() for p in parts if p.lower() != 'nan' and p.strip() != '']
    
    # Inhe '_' se jod de (Example: "Rainfall_Monsoon_Total")
    col_name = "_".join(clean_parts)
    new_columns.append(col_name)

In [160]:
df_final = pd.read_excel("./Pre-Data/2012-2013.xlsx", skiprows=11, header=None)

In [161]:
df_final.columns = new_columns

In [162]:
if df_final.iloc[0,0] == 'S.No': 
    df_final = df_final.iloc[1:].reset_index(drop=True)

In [163]:
print("New Columns Sample:", df_final.columns[:5])
print(df_final.head())

New Columns Sample: Index(['S.No', 'STATE', 'DISTRICT', 'ASSESSMENT UNIT', 'Rainfall (mm)_C'], dtype='object')
    S.No        STATE  DISTRICT  ASSESSMENT UNIT  Rainfall (mm)_C  \
0      1  WEST BENGAL       NaN              NaN      1404.032787
1  Total          NaN       NaN              NaN      1404.032787

   Rainfall (mm)_NC  Rainfall (mm)_PQ  Rainfall (mm)_Total  \
0       1852.432677                 0           1728.60906
1       1852.432677                 0           1728.60906

   Total Geographical Area (ha)_Recharge Worthy Area (ha)_C  \
0                                            2003938
1                                            2003938

   Total Geographical Area (ha)_Recharge Worthy Area (ha)_NC  ...  \
0                                            5252881          ...
1                                            5252881          ...

   Total Confined Ground Water Resources (ham)_Other Parameters Present_Fresh  \
0                                                  0
1                                                  0

   Total Confined Ground Water Resources (ham)_Other Parameters Present_Saline  \
0                                                NaN
1                                                NaN

   Dynamic Semi Confined Ground Water Resources (ham)_Other Parameters Present_Fresh  \
0                                                NaN
1                                                NaN

   Dynamic Semi Confined Ground Water Resources (ham)_Other Parameters Present_Saline  \
0                                                NaN
1                                                NaN

   In-Storage Semi Confined Ground Water Resources (ham)_Other Parameters Present_Fresh  \
0                                                NaN
1                                                NaN

   In-Storage Semi Confined Ground Water Resources (ham)_Other Parameters Present_Saline  \
0                                                NaN
1                                                NaN

   Total Semi-Confined Ground Water Resources (ham)_Other Parameters Present_Fresh  \
0                                                NaN
1                                                NaN

   Total Semi-Confined Ground Water Resources (ham)_Other Parameters Present_Saline  \
0                                                NaN
1                                                NaN

   Total Ground Water Availability in the area (ham)_Other Parameters Present_Fresh  \
0                                        2434876.575
1                                        2434876.575

   Total Ground Water Availability in the area (ham)_Other Parameters Present_Saline
0                                                  0
1                                                  0

[2 rows x 153 columns]

In [164]:
df_final.to_csv('new_2012-2013.csv', index=False)